# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0002_auto_20171030_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
