# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0003_newspost_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='post_videos',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
