# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0004_auto_20171030_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='post_text',
        ),
        migrations.AddField(
            model_name='newspost',
            name='post_content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
