# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0005_auto_20171030_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='is_published',
            new_name='is_approved',
        ),
    ]
