# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0010_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_header',
            field=models.CharField(max_length=255),
        ),
    ]
