# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0011_auto_20171111_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='post_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
