# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0013_auto_20171117_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_category',
            field=models.CharField(choices=[('EAP', 'Economics & Politics'), ('WRD', 'World'), ('AUT', 'Auto'), ('PPL', 'People'), ('TCH', 'Tech'), ('SPR', 'Sport'), ('CBS', 'Cybersport'), ('RLT', 'Realty'), ('BSN', 'Business'), ('SCY', 'Society'), ('ACS', 'Accidents'), ('OTR', 'Other'), ('HLT', 'Health')], default='OTR', max_length=3),
        ),
    ]
