# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0014_auto_20171117_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_header',
            field=models.TextField(),
        ),
    ]
