# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0015_auto_20171117_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_icon', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZNEWS.Category'),
        ),
    ]
