# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0016_auto_20171119_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZNEWS.Category'),
        ),
    ]
