# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0017_auto_20171119_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
