# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0018_auto_20171119_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZNEWS.Category'),
        ),
    ]
