# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0019_auto_20171119_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
