# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0020_auto_20171119_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_header',
            field=models.TextField(blank=True, default='There must be header', null=True),
        ),
    ]
