# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0022_newspost_what_to_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='post_content_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZNEWS.Photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, default='media/notebook.png', null=True, upload_to='media'),
        ),
    ]
