# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0026_auto_20171204_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='nsuser',
            name='news_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsuser',
            name='news_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsuser',
            name='news_rejected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsuser',
            name='news_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
