# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0027_auto_20171211_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsuser',
            name='news_added',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nsuser',
            name='news_read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nsuser',
            name='news_rejected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nsuser',
            name='news_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
