# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZNEWS', '0028_auto_20171211_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsReadByUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='newspost',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='CheckStatus',
        ),
        migrations.AddField(
            model_name='isreadbyuserstatus',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZNEWS.NewsPost'),
        ),
        migrations.AddField(
            model_name='isreadbyuserstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
